### ISSUE TITLE
下了源码后，测试时会出现这个错误，是什么情况？

### ISSUE THREAD

**Issue by fuyicheng1212** [tencentyun/wafer2-startup#152]
Error: ERR_HEADER_MISSED
    at authorization (/data/release/node-weapp-demo/node_modules/wafer-node-sdk/lib/auth/index.js:28:15)
    at authorizationMiddleware (/data/release/node-weapp-demo/node_modules/wafer-node-sdk/lib/auth/index.js:102:12)
    at dispatch (/data/release/node-weapp-demo/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/data/release/node-weapp-demo/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /data/release/node-weapp-demo/node_modules/koa-router/lib/router.js:345:16
    at dispatch (/data/release/node-weapp-demo/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /data/release/node-weapp-demo/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/data/release/node-weapp-demo/node_modules/koa-router/lib/router.js:350:31)
    at dispatch (/data/release/node-weapp-demo/node_modules/koa-compose/index.js:42:32)
    at next (/data/release/node-weapp-demo/node_modules/koa-compose/index.js:43:18)
    at parseBody.then.body (/data/release/node-weapp-demo/node_modules/koa-bodyparser/index.js:74:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by jas0ncn** [comment]
修改了什么吗？
https://github.com/tencentyun/wafer2-node-sdk/blob/d4bf5b0f30756c112c445a741808a55363b4efe8/lib/auth/index.js#L26
