### ISSUE TITLE
配置本地开发环境时，执行sql脚本时报错

### ISSUE THREAD

**Issue by YvanMao** [tencentyun/wafer2-startup#55]
node v8.4.0
mysql  Ver 14.14 Distrib 5.7.19, for macos10.12 (x86_64) using  EditLine wrapper

执行node tools/initdb.js报错，错误日志

Unhandled rejection Error: Error: ER_BAD_DB_ERROR: Unknown database 'cauth'
    at DB.raw.then.err (/Users/mao/myf/wxapp/code/wafer2-startup/server/tools/initdb.js:41:11)
    at tryCatcher (/Users/mao/myf/wxapp/code/wafer2-startup/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mao/myf/wxapp/code/wafer2-startup/server/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mao/myf/wxapp/code/wafer2-startup/server/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/mao/myf/wxapp/code/wafer2-startup/server/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/mao/myf/wxapp/code/wafer2-startup/server/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/mao/myf/wxapp/code/wafer2-startup/server/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/mao/myf/wxapp/code/wafer2-startup/server/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/mao/myf/wxapp/code/wafer2-startup/server/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

**Comment by YvanMao** [comment]
手动在mysql里创建一个cAuth,就能执行通过了
